require("core.global")
require("core.options")
require("keymaps")
require("core.events")
require("winbar")
require("commands")
require("core.lazyplug").setup()

local conf = require("conf")
vim.cmd(string.format("colorscheme %s", conf.theme))
