vim.cmd.highlight("clear")
vim.o.termguicolors = true
vim.g.colors_name = "grubby"

local c = {
	bg_dim = "#252423",
	bg0 = "#32302f",
	bg1 = "#3c3836",
	bg2 = "#3c3836",
	bg3 = "#504945",
	bg4 = "#504945",
	bg5 = "#665c54",
	bg_statusline1 = "#3c3836",
	bg_statusline2 = "#46413e",
	bg_statusline3 = "#5b534d",
	bg_visual_red = "#543937",
	bg_visual_yellow = "#574833",
	bg_visual_green = "#424a3e",
	bg_visual_blue = "#404946",
	bg_visual_purple = "#4b3e45",
	bg_diff_red = "#472322",
	bg_diff_green = "#3d4220",
	bg_diff_blue = "#0f3a42",
	bg_current_word = "#45403d",

	grey0 = "#7c6f64",
	grey1 = "#928374",
	grey2 = "#a89984",

	fg0 = "#d4be98",
	fg1 = "#ddc7a1",
	red = "#ea6962",
	orange = "#e78a4e",
	yellow = "#d8a657",
	green = "#a9b665",
	aqua = "#89b482",
	blue = "#7daea3",
	purple = "#d3869b",
	bg_red = "#ea6962",
	bg_green = "#a9b665",
	bg_yellow = "#d8a657",
}

---@type table<string,vim.api.keyset.highlight>
local groups = vim.tbl_extend("error", {}, {
	-- Builtins.
	Boolean = { fg = c.purple },
	Number = { fg = c.purple },
	Float = { fg = c.purple },
	PreProc = { fg = c.purple },
	PreCondit = { fg = c.purple },
	Include = { fg = c.purple },
	Define = { fg = c.purple },
	Conditional = { fg = c.red },
	Repeat = { fg = c.red },
	Keyword = { fg = c.red },
	Typedef = { fg = c.red },
	Exception = { fg = c.red },
	Statement = { fg = c.red },
	Error = { fg = c.red },
	StorageClass = { fg = c.orange },
	Tag = { fg = c.orange },
	Label = { fg = c.orange },
	Structure = { fg = c.orange },
	Operator = { fg = c.orange },
	Title = { fg = c.orange, bold = true },
	Special = { fg = c.yellow },
	SpecialChar = { fg = c.yellow },
	Type = { fg = c.yellow },
	Function = { fg = c.green, bold = true },
	String = { fg = c.green },
	Character = { fg = c.green },
	Constant = { fg = c.aqua },
	Macro = { fg = c.aqua },
	Identifier = { fg = c.blue },
	Todo = { fg = c.bg0, bg = c.blue, bold = true },
	Comment = { fg = c.grey1, italic = true },
	SpecialComment = { fg = c.grey1, italic = true },
	Delimiter = { fg = c.fg0 },
	Ignore = { fg = c.grey1 },
	Underlined = { underline = true },

	Normal = { fg = c.fg0, bg = c.bg0 },
	Terminal = { fg = c.fg0, bg = c.bg0 },
	EndOfBuffer = { fg = c.bg0 },
	Folded = { fg = c.grey1, bg = c.bg2 },
	SignColumn = { fg = c.fg0 },
	FoldColumn = { fg = c.grey0 },

	IncSearch = { fg = c.bg0, bg = c.bg_red },
	Search = { fg = c.bg0, bg = c.bg_green },
	CurSearch = { link = "IncSearch" },

	ColorColumn = { bg = c.bg2 },
	Conceal = { fg = c.grey0 },
	Cursor = { reverse = true },
	lCursor = { link = "Cursor" },
	CursorLine = { bg = c.bg1 },
	CursorColumn = { bg = c.bg1 },
	LineNr = { fg = c.bg5 },
	CursorLineNr = { fg = c.grey1, bold = true },

	-- Diff
	DiffAdd = { bg = c.bg_diff_green },
	DiffChange = { bg = c.bg_diff_blue },
	DiffDelete = { bg = c.bg_diff_red },
	DiffText = { fg = c.bg0, bg = c.blue },

	Directory = { fg = c.green },
	ErrorMsg = { fg = c.red, bold = true, underline = true },
	WarningMsg = { fg = c.yellow, bold = true },
	ModeMsg = { fg = c.fg0, bold = true },
	MoreMsg = { fg = c.yellow, bold = true },
	MatchParen = { bg = c.bg4 },
	NonText = { fg = c.bg5 },
	Whitespace = { fg = c.bg5 },
	SpecialKey = { fg = c.orange },

	Pmenu = { fg = c.fg1, bg = c.bg3 },
	PmenuSbar = { bg = c.bg3 },
	PmenuSel = { fg = c.bg3, bg = c.grey2 },
	Wildmenu = { link = "PmenuSel" },
	PmenuThumb = { bg = c.grey0 },

	-- Float
	NormalFloat = { fg = c.fg1, bg = c.bg3 },
	FloatBorder = { fg = c.grey1, bg = c.bg3 },
	FloatTitle = { fg = c.orange, bg = c.bg3, bold = true },

	Question = { fg = c.yellow },

	--Spell
	SpellBad = { underline = true, sp = c.red },
	SpellCap = { underline = true, sp = c.blue },
	SpellLocal = { underline = true, sp = c.aqua },
	SpellRare = { underline = true, sp = c.purple },

	VertSplit = { fg = c.bg5 },
	WinSeparator = { link = "VertSplit" },

	Visual = { bg = c.bg3 },
	VisualNOS = { bg = c.bg3 },

	Substitute = { fg = c.bg0, bg = c.yellow },

	-- LSP
	DiagnosticDeprecated = { strikethrough = true, sp = c.fg0 },
	DiagnosticError = { fg = c.red },
	DiagnosticFloatingError = { fg = c.red },
	DiagnosticFloatingHint = { fg = c.purple },
	DiagnosticFloatingInfo = { fg = c.blue },
	DiagnosticFloatingWarn = { fg = c.yellow },
	DiagnosticHint = { fg = c.purple },
	DiagnosticInfo = { fg = c.purple },
	DiagnosticUnderlineError = { undercurl = true, sp = c.red },
	DiagnosticUnderlineHint = { undercurl = true, sp = c.purple },
	DiagnosticUnderlineInfo = { undercurl = true, sp = c.blue },
	DiagnosticUnderlineWarn = { undercurl = true, sp = c.yellow },
	DiagnosticUnnecessary = { fg = c.grey1, italic = true },
	DiagnosticVirtualTextError = { fg = c.red },
	DiagnosticVirtualTextHint = { fg = c.purple },
	DiagnosticVirtualTextInfo = { fg = c.blue },
	DiagnosticVirtualTextWarn = { fg = c.yellow },
	DiagnosticWarn = { fg = c.yellow, bg = c.bg_visual_yellow },
	LspCodeLens = { fg = c.blue },
	LspFloatWinBorder = { fg = c.bg0, bg = c.bg0 },
	LspInlayHint = { fg = c.grey0, bg = c.bg_dim },
	LspReferenceRead = { bg = c.bg4 },
	LspReferenceText = {},
	LspReferenceWrite = { bg = c.bg4 },
	LspSignatureActiveParameter = { link = "Search" },

	-- Treesitter
	["@annotation"] = { fg = c.purple },
	["@attribute"] = { fg = c.purple },
	["@boolean"] = { fg = c.purple },
	["@character"] = { fg = c.aqua },
	["@constant"] = { fg = c.fg0 },
	["@constant.builtin"] = { fg = c.purple, italic = true },
	["@constant.macro"] = { fg = c.purple, italic = true },
	["@constructor"] = { fg = c.green, bold = true },
	["@error"] = { fg = c.red },
	["@function"] = { fg = c.green, bold = true },
	["@function.builtin"] = { fg = c.green, bold = true },
	["@function.macro"] = { fg = c.green, bold = true },
	["@function.method"] = { fg = c.green, bold = true },
	["@keyword"] = { fg = c.red },
	["@keyword.conditional"] = { fg = c.red },
	["@keyword.exception"] = { fg = c.red },
	["@keyword.function"] = { fg = c.red },
	["@keyword.function.ruby"] = { fg = c.red },
	["@keyword.include"] = { fg = c.red },
	["@keyword.operator"] = { fg = c.orange },
	["@keyword.repeat"] = { fg = c.red },
	["@label"] = { fg = c.orange },
	["@markup"] = { fg = c.orange },
	["@markup.emphasis"] = { italic = true },
	["@markup.heading"] = { fg = c.orange, bold = true },

	["@markup.link"] = { fg = c.orange, bold = true },
	["@markup.link.uri"] = { fg = c.yellow, italic = true },
	["@markup.list"] = { fg = c.cyan },
	["@markup.raw"] = { fg = c.yellow },
	["@markup.strong"] = { fg = c.orange, bold = true },
	["@markup.underline"] = { fg = c.orange },
	["@module"] = { fg = c.orange },
	["@number"] = { fg = c.purple },
	["@number.float"] = { fg = c.green },
	["@operator"] = { fg = c.pink },
	["@parameter.reference"] = { fg = c.orange },
	["@property"] = { fg = c.blue },
	["@punctuation.bracket"] = { fg = c.fg },
	["@punctuation.delimiter"] = { fg = c.fg },
	["@string"] = { fg = c.aqua },
	["@string.escape"] = { fg = c.green },
	["@string.regexp"] = { fg = c.green },
	["@string.special.symbol"] = { fg = c.purple },
	["@structure"] = { fg = c.purple },
	["@tag"] = { fg = c.orange },
	["@tag.attribute"] = { fg = c.green },
	["@tag.delimiter"] = { fg = c.green },
	["@type"] = { fg = c.yellow, italic = true },
	["@type.builtin"] = { fg = c.cyan, italic = true },
	["@type.qualifier"] = { fg = c.pink },
	["@variable"] = { fg = c.fg0 },
	["@variable.builtin"] = { fg = c.purple },
	["@variable.member"] = { fg = c.blue },
	["@variable.parameter"] = { fg = c.orange },
})

for group, opts in pairs(groups) do
	vim.api.nvim_set_hl(0, group, opts)
end
