keys:
  - &machine-nixbox age1y97f9hg6fa0zul4tz2vg9l4tktdtl3mw4tv2exh4zv0gd3y6wydsqw6hn5
  - &lab age1g7q5t66wxgrzc6w89sfpfhm4ajmh55t7wy03q2gq6jllmykg03lqsu0yx8
creation_rules:
  - path_regex: ^shared.yaml$
    key_groups:
      - age:
          - *machine-nixbox
          - *lab
  - path_regex: homelab.yaml
    key_groups:
      - age:
          - *machine-nixbox
          - *lab
